export const GET_HEROES_REQUEST = 'GET_HEROES_REQUEST';
export const GET_HEROES_SUCCESS = 'GET_HEROES_SUCCESS';
export const GET_HEROES_ERROR = 'GET_HEROES_ERROR';
export const GET_HEROES_SAGA = 'GET_HEROES_SAGA';
export const GET_COMICS_REQUEST = 'GET_COMICS_REQUEST';
export const GET_COMICS_SUCCESS = 'GET_COMICS_SUCCESS';
export const GET_COMICS_ERROR = 'GET_COMICS_ERROR';
export const GET_COMICS_SAGA = 'GET_COMICS_SAGA';
